version: '3.3'

services:
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - ./.env
    container_name: frontend
    stdin_open: true
    restart: always
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
  
  backend:
    ports:
      - "8081:8081"
    container_name: backend
    restart: always
    env_file:
      - ./.env
    environment:
      - PORT=8081
    build:
      context: ./backend
      dockerfile: backend.dockerfile