version: '2'

services:
  client:
    build: client
    ports:
      - "3000:8080"
    container_name: client
    stdin_open: true
    restart: always
  
  server:
    build: server
    ports:
      - "3001:8081"
    container_name: server
    restart: always