version: '3.3'

services:
  client:
    build: client
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - ./.env
    container_name: client
    stdin_open: true
    restart: always
    build:
      context: ./client
      dockerfile: frontend.dockerfile
  
  server:
    ports:
      - "8081:8081"
    container_name: server
    restart: always
    env_file:
      - ./.env
    environment:
      - PORT=8081
    build:
      context: ./server
      dockerfile: backend.dockerfile